ICommentRepo updaten, Added functions in CommentRepo and small change…
Databasserne/HackerNews-Backend pull request #16
Opened 2017-10-30 15:41 UTC by JonasSimonsen

Check it out :P

2017-10-30 15:44 UTC, 1martinkarlsen commented on src/main/java/com/databasserne/hackernews/repo/ICommentRepo.java
> +     *
Javadoc mangler

2017-10-30 15:46 UTC, 1martinkarlsen commented on src/main/java/com/databasserne/hackernews/resource/CommentResource.java
> +            return null;
Den her returner bare null, så man får ikke noget response, medmindre det er en fejl

2017-10-30 15:46 UTC, 1martinkarlsen commented on src/main/java/com/databasserne/hackernews/resource/CommentResource.java
> +            return null;
Returner også kun null

2017-10-30 15:46 UTC, 1martinkarlsen commented on src/main/java/com/databasserne/hackernews/resource/CommentResource.java
> +            return null;
Returner kun null

2017-10-30 15:47 UTC, 1martinkarlsen commented on src/main/java/com/databasserne/hackernews/service/CommentService.java
> +}
Alle metoderne smider exceptions. De skal jo gøre noget

2017-10-30 15:47 UTC, 1martinkarlsen commented on src/main/resources/META-INF/persistence.xml
> +            <property name="javax.persistence.jdbc.password" value="root"/>
Password skal ikke med

2017-10-30 15:47 UTC, 1martinkarlsen commented on src/main/resources/META-INF/persistence.xml
> +            <property name="javax.persistence.jdbc.password" value="root"/>
Password skal ikke med

2017-10-30 15:48 UTC, 1martinkarlsen requested changes
Der er generelt nogle ting der skal laves færdigt, før den kan merges.
Se comments, rundt omkring.

2017-10-31 22:05 UTC, 1martinkarlsen commented on src/main/java/com/databasserne/hackernews/repo/impl/CommentRepo.java
> +            em.createQuery("SELECT ");
Denne ser ikke ud til at være færdig

2017-10-31 22:07 UTC, 1martinkarlsen commented on src/test/java/com/databasserne/hackernews/repo/CommentRepoTest.java
> +//    }
Udkommenteret test?

2017-10-31 22:07 UTC, KSWorm93 commented on src/test/java/com/databasserne/hackernews/repo/CommentRepoTest.java
> +//    }
du ser på outdated code??

2017-10-31 22:07 UTC, 1martinkarlsen commented on src/test/java/com/databasserne/hackernews/repo/CommentRepoTest.java
> +//    }
Udkommenteret test?

2017-10-31 22:08 UTC, 1martinkarlsen requested changes
Tjek kommentarene :-)

2017-10-31 22:13 UTC, 1martinkarlsen commented on src/main/java/com/databasserne/hackernews/resource/CommentResource.java
>              return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(gson.toJson(response)).type(MediaType.APPLICATION_JSON).build();
forstår ikke det her? Et API kald til at sende http 500 error?

2017-10-31 22:16 UTC, KSWorm93 commented on src/main/java/com/databasserne/hackernews/resource/CommentResource.java
>              return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(gson.toJson(response)).type(MediaType.APPLICATION_JSON).build();
Har bare gjort på samme måde som du selv gjorde i PostResource

2017-10-31 22:23 UTC, 1martinkarlsen approved these changes

2017-10-31 22:23 UTC, merged